#include <xmlMaker.h>

XmlMaker::XmlMaker(std::string p)
{
	this->path = p + "thumbcaches.xml";
	file = new FileWriter(path, 8*1024*1024);
}

void XmlMaker::writeXml(std::vector<PartitionFiles> &p, bool edb)
{
	edbOnly = edb;
	//(*file).open(path.c_str(), std::fstream::out);

	(*file) << "<Thumbcache-Extractor>" << "\n";
	(*file) << "\t<Author> Christian Zoubek, Sabine Seufert </Author>" << "\n";
	(*file) << "\t<Info> Autogenerated by Thumby-Extractor (c)crisbi </Info>" << "\n";
	(*file) << "\t<Partition-Count> " << p.size() << " </Partition-Count>" << "\n";
	if (p.empty())
	{
		//(*file) << "\tNo relevant partition found!" << "\n";
	}
	for (auto in : p)
	{
		writePartition(in);
	}
	(*file) << "</Thumbcache-Extractor>" << "\n";
	file->closeFile();
	//(*file).close();
}

std::string XmlMaker::cleanString(std::string &in)
{
	std::string ret = in;
	size_t off = 0;
	while ((off=ret.find("\\",off)) != std::string::npos)
	{
		ret.replace(off,1,"/");
		off += 1;
	}
	off=0;
	while ((off=ret.find("_",off)) != std::string::npos)
	{
		ret.insert(off, "\\");
		off += 2;
	}
	return ret;
}

void XmlMaker::writeExif(pictureInfo &pic)
{
	(*file) << "\t\t\t\t\t\t";
	(*file) << "<Exif>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Resolution> " << pic.hRes << "x" << pic.vRes << " </Resolution>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Bitdepth> " << pic.bitDepth << " </Bitdepth>" << "\n";
	(*file) << "\t\t\t\t\t\t";
	(*file) << "</Exif>" << "\n";
}

void XmlMaker::writeSys(systemInfo &sys)
{
	(*file) << "\t\t\t\t\t\t";
	(*file) << "<Systeminfo>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Datasize unit=\"KB\" size=\"" << std::to_string(sys.size/1024) << "\" />" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Dates>" << "\n";
	(*file) << "\t\t\t\t\t\t\t\t" << "<Accessed> " << sys.dateAccessed << " </Accessed>" << "\n";
	(*file) << "\t\t\t\t\t\t\t\t" << "<Modified> " << sys.dateModified << " </Modified>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "</Dates>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<MIME-Type> " << sys.MIMEType << " </MIME-Type>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Filename> " << sys.fileName << " </Filename>" << "\n";
	(*file) << "\t\t\t\t\t\t\t";
	(*file) << "<Owner> " << sys.owner << " </Owner>" << "\n";
	(*file) << "\t\t\t\t\t\t";
	(*file) << "</Systeminfo>" << "\n";
}

void XmlMaker::writeMeta(dbInfo &db)
{
	(*file) << "\t\t\t\t\t\t<Thumbsize unit = \"KB\" size=\"" << std::to_string(db.dataSize/1024) << "\" />" << "\n";
	(*file) << "\t\t\t\t\t\t<Md5Sum> " << db.md5Sum << " </Md5Sum>" << "\n";
}

void XmlMaker::writeFile(FileInfo &info, bool write)
{
	if (edbOnly == true && info.second.foundInEDB == false)
		return;

	if (info.second.foundInEDB != write)
		return;
	std::string tmp = info.second.absoluteFileName;
	std::string sys = "convert " + tmp + " " + tmp + ".png";
	if (system(sys.c_str()))
	{}
	(*file) << "\t\t\t\t<Thumbnail>" << "\n";
	(*file) << "\t\t\t\t\t<img src=\"" << tmp << ".png\"/>"<< "\n";
	(*file) << "\t\t\t\t\t<Meta>" << "\n";

	writeMeta(info.second);
	if (info.second.foundInEDB==true)
	{
		writeSys(info.first.sysInfo);
		writeExif(info.first.picInfo);
	}
	(*file) << "\t\t\t\t\t</Meta>" << "\n";
	(*file) << "\t\t\t\t</Thumbnail>" << "\n";
}

void XmlMaker::writeThumb(ThumbCacheFiles &tcf)
{
	(*file) << "\t\t\t<" << tcf.first << ">" << "\n";
	(*file) << "\t\t\t\t<Filecount> " << tcf.second.size() << " </Filecount>" << "\n";
	(*file) << "\t\t\t\t<Ese_linked>"<< "\n";
	for (auto in : tcf.second)
	{
		writeFile(in, true);
	}
	(*file) << "\t\t\t\t</Ese_linked>"<< "\n";
	(*file) << "\t\t\t\t<Thumbnails_only>"<< "\n";
	for (auto in : tcf.second)
	{
		writeFile(in, false);
	}
	(*file) << "\t\t\t\t</Thumbnails_only>"<< "\n";
	(*file) << "\t\t\t\t</" << tcf.first << ">" << "\n";
}

void XmlMaker::writeUser(UserFiles &user)
{
	(*file) << "\t\t<User name=\"" << user.first << "\">" << "\n";
	for (auto in : user.second)
	{
		writeThumb(in);
	}
	(*file) << "\t\t</User>" << "\n";
}

void XmlMaker::writePartition(PartitionFiles &partition)
{
	(*file) << "\t<NTFS-Partition>" << "\n";
	(*file) << "\t\t<Offset> " << partition.first << " </Offset>"<< "\n";	
	(*file) << "\t\t<Usercount>" << "\n";
	(*file) << "\t\t\t" << partition.second.size() << "\n";
	(*file) << "\t\t</Usercount>" << "\n";
	for (auto in : partition.second)
	{
		writeUser(in);
	}
	(*file) << "\t</NTFS-Partition>";
	(*file) << "\n";
}

